# ABOUTME: Cloud-init configuration for initial VM setup
# Uses NoCloud datasource for local KVM/libvirt provisioning

#cloud-config

# Explicit NoCloud datasource prevents waiting for cloud metadata (AWS/Azure/etc)
# This is the standard approach for local VM development
datasource_list: [ NoCloud, None ]
datasource:
  NoCloud:
    seedfrom: /dev/sr0  # Cloud-init ISO device

hostname: ubuntu-vm
fqdn: ubuntu-vm.local

# Create user
users:
  - name: mr
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_public_key}

# Set timezone
timezone: UTC

# Minimal setup - no package installation (Ansible handles everything)
# Cloud image already has openssh-server and python3 pre-installed

# Enable SSH
ssh_pwauth: false
disable_root: true
