# ABOUTME: Cloud-init configuration for initial VM setup

#cloud-config
hostname: ubuntu-vm
fqdn: ubuntu-vm.local

# Create user
users:
  - name: mr
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_public_key}

# Set timezone
timezone: UTC

# Update and upgrade packages
package_update: true
package_upgrade: true

# Install base packages
packages:
  - openssh-server
  - git
  - curl
  - build-essential
  - python3
  - python3-pip

# Enable SSH
ssh_pwauth: false
disable_root: true

# Run commands on first boot
runcmd:
  - systemctl enable ssh
  - systemctl start ssh
