# ABOUTME: Ansible inventory fragment for ${vm_name} (generated by Terraform)
# Note: [vms] header is added by merge step, not per-fragment
%{ if vm_ip != "" ~}
${vm_ip} ansible_user=${vm_user} ansible_ssh_private_key_file=~/.ssh/vm_key ansible_ssh_common_args='-o StrictHostKeyChecking=no' ansible_python_interpreter=/usr/bin/python3 vm_name=${vm_name}%{ if dotfiles_local_path != "" } dotfiles_local_path="${dotfiles_local_path}"%{ endif }
%{ endif ~}
